---
- name: Frankendancer Installation
  hosts: localhost
  become: true
  become_user: root
  gather_facts: true

  tasks:
    - name: Install rustup and set stable toolchain as default
      ansible.builtin.apt:
        name: "rustup"
        state: present
      ansible.builtin.shell:
        cmd: "rustup default stable"