---
- name: Frankendancer Installation
  hosts: localhost
  become: true
  become_user: root
  gather_facts: true

  tasks:
    - name: Install rustup
      ansible.builtin.apt:
        name: "rustup"
        state: present
    - name: Set stable toolchain as default and run cargo for testing
      ansible.builtin.shell:
        cmd: |
          rustup default stable
          cargo
    - name: Register return value
      ansible.builtin.shell:
        cmd: echo $?
      register: cargo_status
      changed_when: false
    - name: __DEBUG__ Check cargo variable value
      ansible.builtin.debug:
        msg: "{{ cargo_status.stdout }}"